# docker-compose.yml文件的版本
version: "3.3"
# 管理的服务
services:
  redis:
    # 指定镜像
    image: redis:latest
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      # 目录映射
      - "${REDIS_DIR}/conf:/usr/local/etc/redis"
      - "${REDIS_DIR}/data:/data"
    command: ["redis-server","appendonly","yes"，“requirepass”，“123456”]
    # --requirepass 123456

#   mysql:
#     image: mysql:latest
#     ports:
#       - 3306:3306
#     volumes:
#       - "${MYSQL_DIR}/data:/var/lib/mysql"
#       - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
#     environment:
#       # 环境变量
#       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}