version: "3.3"
services:
    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        hostname: 'gitlab.tops.com'
        container_name: 'tops-gitlab'
        ports:
            - '81:80'
            - '443:443'
            - '23:22'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url "http://gitlab.tops.com"
                gitlab_rails['gitlab_shell_ssh_port'] = 23
                gitlab_rails['time_zone'] = 'Asia/Shanghai'
                # email setting
                gitlab_rails['smtp_enable'] = true
                gitlab_rails['smtp_address'] = "smtp.163.com"
                gitlab_rails['smtp_port'] = 25
                gitlab_rails['smtp_user_name'] = "nice@163.com"
                gitlab_rails['smtp_password'] = "xxx"
                gitlab_rails['smtp_domain'] = "163.com"
                gitlab_rails['smtp_authentication'] = "login"
                gitlab_rails['smtp_enable_starttls_auto'] = true
                gitlab_rails['gitlab_email_from'] = "nice@163.com"
                gitlab_rails['smtp_tls'] = false
                gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
                user["git_user_email"] = "nice@163.com"
        volumes:
            - './data/gitlab/config:/etc/gitlab'
            - './data/gitlab/logs:/var/log/gitlab'
            - './data/gitlab/data:/var/opt/gitlab'
        networks:
            - gitlab_net
  runner:
    image: 'gitlab/gitlab-runner:latest'
    container_name: 'gitlab-runner'
    restart: always
    volumes:
      - './data/gitlab-runner/config:/etc/gitlab-runner'
      # - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab_net
    extra_hosts:
      - "gitlab.tops.com:192.168.240.2"

networks:
    gitlab_net:
        name: gitlab_net