version: "3.3"
services:
  jenkins:
    image: jenkinsci/blueocean:latest
    container_name: tops_jenkins
    user: root
    restart: always
    ports:
      - "9090:8080"
      - "50000:5000"
    volumes:
      - "./data:/var/jenkins_home"
      # - "/var/run/docker.sock:/var/run/docker.sock"