version: '3.3'

services:
  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgre:/var/lib/postgresql
      - ./postgre/data:/var/lib/postgresql/data

  sonar_server:
    image: sonarqube
    ports: 
      - "9000:9000"
      - "9092:9092"
    restart: always
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres_db:5432/sonar?charSet=UNICODE
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    links:
      - postgres_db
    # entrypoint: |
    #   bash -c 'bash -s <<EOF
    #   trap "break;exit" SIGHUP SIGINT SIGTERM
    #   sysctl -w vm.max_map_count=262144 && ./bin/run.sh
    #   EOF'

# volumes:
#   # postgresql_data:
#   sonarqube_bundled-plugins:
#   sonarqube_conf:
#   sonarqube_data:
#   sonarqube_db:
#   sonarqube_extensions:
